// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class InitWithAkSkRequestData;

@interface InitWithAkSkRequestData : NSObject
@property(nonatomic, copy, nullable) NSString * ak;
@property(nonatomic, copy, nullable) NSString * sk;
@end

/// The codec used by OcrHostApi.
NSObject<FlutterMessageCodec> *OcrHostApiGetCodec(void);

@protocol OcrHostApi
- (void)initWithAkSkRequest:(nullable InitWithAkSkRequestData *)request completion:(void(^)(FlutterError *_Nullable))completion;
- (void)recognizeIdCardFrontNativeWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)recognizeIdCardBackNativeWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)initCameraNativeWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)releaseCameraNativeWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void OcrHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<OcrHostApi> *_Nullable api);

/// The codec used by RecognizeListenerFlutterApi.
NSObject<FlutterMessageCodec> *RecognizeListenerFlutterApiGetCodec(void);

@interface RecognizeListenerFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onReceivedResultResult:(NSString *)result completion:(void(^)(NSError *_Nullable))completion;
- (void)onReceivedErrorDescription:(NSString *)description completion:(void(^)(NSError *_Nullable))completion;
- (void)onReceivedCancelWithCompletion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
