name: baidu_ocr_plugin
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  pigeon: ^1.0.12 # flutter pub run pigeon --input "pigeons/messages.dart"

flutter:
  plugin:
    platforms:
      android:
        package: ren.yanhao.baidu_ocr_plugin
        pluginClass: BaiduOcrPlugin
