name: baidu_ocr_plugin
description: 百度文字识别 OCR
repository: https://github.com/yanhao98/baidu_ocr_plugin
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.0.0

dev_dependencies:

  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  pigeon: ^1.0.12

flutter:
  plugin:
    platforms:
      android:
        package: ren.yanhao.baidu_ocr_plugin
        pluginClass: BaiduOcrPlugin
      ios:
        pluginClass: BaiduOcrPlugin